apiVersion: v1
kind: LimitRange
metadata:
  name: default-container
spec:
  limits:
  - default:
      cpu: 200m
      memory: 100Mi
    defaultRequest:
      cpu: 100m
      memory: 10Mi
    max:
      cpu: "1"
      memory: 1Gi
    min:
      cpu: 50m
      memory: 5Mi
    type: Container
