apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
    tier: defaults
  name: nginx-defaults
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
        tier: defaults
    spec:
      containers:
      - image: nginxinc/nginx-unprivileged:latest
        name: nginx-unprivileged
        resources: {}
