apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
    spec:
      containers:
      - image: gcr.io/google_containers/pause-amd64:3.0
        name: app
