apiVersion: apps/v1
kind: Deployment
metadata:
  name: quay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
    spec:
      containers:
      - image: quay.io/zlynch/pause-amd64:3.1
        name: app
